---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAhrqVxweJBpTWR8VQqboRaFrfR+NiLxnmcuPOElwooajWnDyjjoLUwKThrxTqp7pkPbKtSg7uRFQFWK5CLtCR7kLsaNWx9+1NkuUKHZ1A+piK13pmaSofkh5HGBHj2lozlArTNDVZ3cTjgubuct61b1G0xUSFUvCOo78wYGf7ml6iTA7Sm6gvfI90//eeq6cwSUevW0Rer907pygMgwsnqa9n6AIHBmtzWtDu+dziNyNWInP2mGv3NazXbXyom6DUlis3Okh6tVRt/xFNNKroh41CfOOdBgG7meVwDL4hcWIM7lL/N4y8ttLjEBFDpnvb/WHjBsKcwTwlHC47asMsz+DP9f6DRozy3Thack9fUzgM+LsCO2iXTfPnay+ry62tLWfH/OBLWWLZ7gkWPpxYt1cd9uIuZbnxYDsEr0l75x9JgQJro6mZKY5wg5hImXDCQQxuZ/sVfYacvZVWnzv/KgF8e5P7/P71VS7CaPs+z8I0lvRZwdVxJAMHu0apEqIvV2CEhUvmLKn6NOAO67ccm3MFRfaB5inHHTvXZxLgG8EjW+EUbkf4bBB8EICjSxYQJ2H1PTXI7aTfRzHTGFaVOivrPwZOYcZhrJcmUXbx8lsVMVC/EloGoPBLKWio8ef5JbylBsJOyQrqDF1T1oVPkqn5p7dpbgedoJpstATmOEZB60gtdw1+uE0R78AKIee+O6NO3xNY4ILx8oBmuo/lZoEUkjMolar5dQy3/qBq260F0lxBFgPUoc8o9daOI2EPaE3ux7BqtYxrnfoxD/tepzlMJsXvBqOB4Khd1b6YPwkvEr1c9vo1/w2EFGJFPlfLEYx/npmOp6uthDwcCmF4z3O5xtX1aZ7cuGEuppXxrC0lWduMdiYkFiLe9PbwT3o9s9VCt3aZIprgJCIX55satqRGefih5zRXeKSykLi7y
  template:
    metadata:
      name: cloudflared-creds
      namespace: cloudflared
