---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-secret
  namespace: couchdb
spec:
  encryptedData:
    admin-password: AgBwi97mO5vHfPJovsVEo7Yw2j45dW4CfVUCimtdbywlzan6uqtrXBxHlEU41mBFhcGVL1ks8P0nR/AO8YvRONT3WqsBsRYUqvc5QrfHLDu7GexPyOHbt4PN4jxZO6hQIvO+dujwKY223Ntm3UwE9Atpoz+WX16D2xYQ0+fh91gRfic8Nz0ywp0ZkOX/5XPcBOk6ziWjk1mZv4jEi/ROoHON+JLg/DSn5BNYrHdJQi/wknJK+gGm+9v/aB3bW4YUwLH86aKarUT4sAYHIXrwxm8t6L7Lu6PRlMqmp66et9AFoY8T3+OAWctPuM8ydY1b5Jzrsi1M2Fs98Y/U3n9vd4/cZxAUl91ktHxks1mzuvywDgIGEzHfYEAPuQhDNNoR/VpWR+87nEcWxYG+A1fDfh9I/hHUxxOflwXukYwAudajejRTF1xWml64d65Q13SeWqD6IS2KSaXO5yZh5K/Tt8MbWJil76Ffli2uECoJ1tL6cRWnmPdTWU/A7LtqraaXAyOrGwZkEaRh9HberkNhN1sqOCfoH7MZy0Gb6ESspFFkXjT61F0yVn4+G2GOTkrjlB81if2ly18i70nKcrYZ88EU8P62i9Sjby3t/GtI0ZYGjKAUZoQx8PBMpQpMp8NHbboMAEK0RLaSjxbgk6qgfNyTBBLHnTneTFvqRjxTd9KNWNc+h/tGaCHqYs0BOYYNfmvIC1ybvfQ1Axxz4TBW/b4Xl0Ml
    admin-user: AgAFOxfHTbFbhoqkl8h2kaTUXdGgQblMcT2J5ZmVCn+i+LnUSkKdAJ/8ebcz1PmlSFB6zUPP7UW5LdBiFoz1pV7pNbU2OIUd4aGCNVKRk/CH+cuqMkWx8RcHlz6HR2FBcwhxUy6VJjuayuir2Z9BsVobbfNgTMOLl8Dqh82aS4Vx9yptsdNxj85MM/9DvKIqofwJ1GSxA7DNtCd+pkdrbkV7IOuEid3YDeTgpl/n8z8HkHqMoecR48dZBmZ0hnWgGzAFKoWRz0b7QmEBiO3GTaVRgcif/4tpTbadFOsVDw13uW84HQV05/gBx+qn2KncBBRLQQxx2NcWAaXrGPd6vlmavtGQ0bSDn/JeggpaCysUkhPEhWvO1B5sBYb4obp8IBIIJ3w6nV2ntKSmTs1tG0yhYFSu3yO+Bmytyqc8IVf+3H12Ht15/xRKi/KFpG0ZUVBN+nm+rJB9odDr6yJ5iOQtAmA0ZENi5iTx1IfVAEOD7/yqIFF/f/T1SjiTTkX0Sn3LA47JD7bFWaXaGcD+o//5/Yr0A+l+Qrm8VGtfH3xpVV/WX2eiSDiZ3uO0fJmPVQ7LNV7sj7fE+0GcyeTXns0I6TmDTj0Wzv8ryOd+lJ6uTbvxRJhcVl1/czgvowuhZOSXw1zDx8F32V9+R9sjMpVq7pohWXsFSY1NhjOenX2Kv3KdUBWF7B1jvGsr6C1aA+K8x8E3kg==
  template:
    metadata:
      name: couchdb-secret
      namespace: couchdb
