apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-config
  namespace: obsidian
data:
  livesync.ini: |
    [httpd]
    enable_cors = true

    [chttpd]
    require_valid_user = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, DELETE, POST, HEAD
