apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
  namespace: obsidian
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
        app.kubernetes.io/name: obsidian
    spec:
      securityContext:
        fsGroup: 5984
      containers:
        - name: couchdb
          image: couchdb:3
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: obsidian-secret
                  key: admin-user
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: obsidian-secret
                  key: admin-password
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: obsidian-data
