apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-data
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 2Gi
