---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: obsidian-secret
  namespace: obsidian
spec:
  encryptedData:
    admin-password: AgAIwVCmnK4ky5eg4v6r1AGdf6Op++IQ48cSa8062vgPTgDsihCwBl247mWQoTWo9T5Y4fmFz2PSacR6X0hDyh4G6IgRu00L6Yqp+PXO1q1ABLBgKRpyskoEr/PywTo/dnj1anIlLugFNSNgyTz12sjKsndPVDhL9PHS1O1JRlyGgNZC6wFEJeUOPOwTb8wNM73hR+2xy+KTdkN5xscsx5TbSx9WEvonpLK9Zprrp5M+zY49sJ4a31WBZgepAcSydMLtA0+LQmo/MnZ3sIII9bBl4Vv9Sv/aNtlhAMBunDwDGghUKHBTOUdCs/d1ToXhKKPYbrd33P5s7YxJMwcCFGoLED7Wl4hgZjRvU3uQXrG0H9DUhKZVWLjr+tLfj50xeWERzokYy+lUk4DYdGj5ikoEIqUAj9IhCIXLoNF9BBAVaikXDNZgKtbsYjEv6M4YCUFnbeOXfPrEZTHglKWNHbQfVSvrVudBSDDrlYrtPX3Kmez8QhWpzL40eEnUGLSnkIadt/G796P7qERVEldpH6oV/EtqroF/yzXG3lca0cUrzGa/kdaG0rE+Vo2lqWmkryNCtBuH4zQ7QAul1ceDsjPchqFUh1vHYo/4dVdK71wtQD7eHCyHAZlxxuTfJrslqjb1g2+u9r6lP1nL7wYHOGIp6u3D730pxa5Y93IcJQcWmY44Edf7bD6YW66HXOn0upVbANS5OosH216cgMObQSrBlkfQ
    admin-user: AgA/8PvK4E2PWqXslAjiV0zYjYrj9yzOBF9k5uC3rlxseIxaN4RQd+kFIOKQ/hLGBFhi9fY3/chT69sraTS8YBdlGSWuNNKEwt7NPF3XMU4v9HF2v2MHIOtzG6rvEBHoc7n0dAsW7sObIbaQlzwRBKoFxdkgun2aGXkeb8mT6m2sV2ksimQgam7aE1LTjmsKC1X4mNVcJH7Ql197TiYLW5l93ptU2b7p+VJi0HCE6+HsHBw0R3fq7K1ytZrHKi2pTzu8jnlXmJhIzPNgBBpI4o3Kx1svkSrEXKbi/BNJpFz/DM7aRLYeGkx0yHXOFa9GP+2s7xs5RSpLZJ225FD1Ci/diV5Di2EM63mIdOln0CzP5KbfbmBlPT4ZcSs9kvSuQYX9XtzhiZC8efu5QxXpsda+G7JsfCpkCQDQ9j2nSd2hNNP2LYCWcwBS+rFQknJ+3Xrvwm8qBJ9/uaaXutfcu2O+EfSExFAoy6aM8uKxMaGXWnUbrp56otSqVzXL8YUHvLs30UkSVYxWVw/Hvves4MEuonAhc5VCi1s637qnbKbNv4TORUSpEdGLSsWQtC2hcocuZu5nKdDRmuIiJ1QNaaJCmTzIwuaUnGD3FlFs+vwcTVS/YrqwyziTqzu4WboNOUhoFZkebQM8Hj8S4YoGTG8YbksnOS3w8IN8vo17X3oqaVRX1CZtWG3+GoZc5hMUqoTYZT0XDQ==
  template:
    metadata:
      name: obsidian-secret
      namespace: obsidian
