# renovate: datasource=github-releases depName=actions/runner
gh_runner_version: "2.335.1"
# renovate: datasource=github-releases depName=opentofu/opentofu
gh_runner_tofu_version: "1.12.3"
gh_runner_repo: "byeich/homelab"
gh_runner_user: "runner"
gh_runner_home: "/home/runner"
gh_runner_labels: "homelab"
