apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  volumeName: pvc-51985288-b2ea-4447-86ab-43e1ea9b7549
  resources:
    requests:
      storage: 5Gi
