---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAyuZyxI5PWfjo7fIZcBK3tqkmCVc3wXhtNPlo6Oocp8ipoRvA09b3vzQRNpBjn7z9SUlS4TD104e3qmyIE0YNcFG5d7INfTXtYB339vJx0USBNo5tMpGiVMTs+qVPvLA0rakJIMeb1U8YM7p4egQqcLy6Z8Uvp39P1ZnNcvtX+TJHX7CeYn1zuJdHRR5f9PSZ7TMT1MNovrjqsu6q988utKhZMZ97kQtTTm+Il+rQ09qn0PD4qlq4XvN1eEWE4fpbPlm2cc4sze+jMGKKo5nt7m43O3Q73P3DESctVxbE4p3gIx2RTKhqbdalZT/9NVRXR8B1/8CJZIAPSK64GjjCBOFis0QFTk5HDlnp99TximIvuRvD00RhGAZk6bAKGFNyMWsaedCFZ+Tto3yEXN/WCAo5SCwj4jlQ+O3T7TgCNV0vCzKixSf59nqInRY8s1CXi2MxkJqHIa8eT+1S1CB9M56W9hn78k05fwZINZyrCklPFoQOcEoDGesg/v5rRmzRaWx+iI158F8y/r3fRzltQNcsN1SNEGPTD4UOAQ8CoXsLgdlia1058BGWGYo0jTSih695KtiYeQfPWB2ahaQQpZ4NDXEIi4ezv5pnMoFkeNzp78RT/jOTZmq1jrSq0FmDzXxRDMvSFJxr7crFFp0Ze3eARLngI5i4x2pbKjEJb4uDW6FZSoJ4NpQrRzxFxMzXloSjKqg6u51TsI7t92+D19Z7r+a8aNPIx7yQ96noc/uXsTm5ByI9TJ426P+ZnRyA3SGVVvO5LExUtMuUYkINR
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
