apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  volumeName: immich-model-cache-restored
  resources:
    requests:
      storage: 10Gi
