---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  encryptedData:
    db-password: AgCIy/7Fb3N0lQBdB5EWdGbXp77NH5Q7AU6SXcRgIHIuqauAnx1/Zih16dz2P6cdaDchz43zbN2/mX7H9rdlZV4CVcWUMQZ0rGfuzald9ctf6a8ux3/bFpQILVRyRzArw+/j6AsnDgy7XfmaK0/Y236nOgqrtuaRGasejoHjxqVDPokwUgyclI3Qnws5UddJoc4/ZmNAiICs+8FLEvS8YcHqO3iSUtmdCitCYJ/HN3anre+XdqNST/BYo5odKyuaQ1mriEfDGLLeSkD8E72VJTu/gsosqewYnLym4GRjIK2bdTyrAUtsimzexWWN4Glv7bd/fhV2fS6sTfLl5qYN860Pc9c4QEfh5rBtgDm/kmuwyDJ5ZVUGto7ufvb9l69vadOU3Z/dux76IkaOBCAf0zAb5T93xUbi7qhNijhhFtCXFF73Tzjpvdo2trGb9O6qxtOK8QSXrFnjR5Upca0hsiOJK93r5wVGrqLrr4LEjwkXqIjmnmq1FxXkK45C7YHGeY072nIVhcmmowBcLvD//mRMKzmwY0exSBG51ppKYahl6lWg4FE68jO+ELllSwqbn1P1O3+GeocbBT7QZ1WUI7X7+4fd/50lzW1VvVElYR2DnMBTZhJ7E0XI8izAQtuqL5ZjgrsW68DiniidfHXlEug0/2BNxiG2ckitt3U97ixWLvWVPl1Bqm5hOdU9Tz4hVbXAO6nHJV4QMRz2IJjoug==
  template:
    metadata:
      name: immich-secret
      namespace: immich
