- name: Base config for Debian LXC
  hosts: lxc_host
  become: true
  tasks:
    - name: apt | update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: apt | install packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - vim
          - htop
          - git
          - sudo
        state: present
    - name: service | Start SSH
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true
    