---
# Default password
pihole_web_password: "changeme"
pihole_interface: "eth0"


# Used in pihole setupVars.conf file copied to /etc/pihole/setupVars.conf on pihole container
pihole_ipv4_address_cidr: "10.0.0.53/24"
pihole_ipv4_gateway: "10.0.0.1"
pihole_dns_1: "1.1.1.1"
pihole_dns_2: "8.8.8.8"
pihole_query_logging: true
pihole_install_web: true
pihole_install_dnsmasq: true
pihole_timezone: "America/New_York"
