apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-5248737533"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-5248737533"
    notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-5248737533"
spec:
  project: default
  source:
    repoURL: https://github.com/byeich/homelab
    targetRevision: argocd-notifs
    path: k8s/apps/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
