apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "5421448913"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "5421448913"
    notifications.argoproj.io/subscribe.on-health-degraded.telegram: "5421448913"
spec:
  project: default
  source:
    repoURL: https://github.com/byeich/homelab
    targetRevision: argocd-notifs
    path: k8s/apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
