apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/byeich/homelab
    targetRevision: argocd-notifs
    path: k8s/apps/obsidian
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
